# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]
        exclude: '^(analysis_manager|query_manager|story_manager|insights_backend)/manage\.py$|^query_manager/core/models\.py$'

  - repo: local
    hooks:
      - id: manage-py-format
        name: format (black & isort)
        entry: python manage.py format
        language: system
        files: \.py$
        exclude: '^core/fulcrum_core/modules/__init__.py$|^commons/commons/db/signals/__init__.py$|^analysis_manager/analysis_manager/patterns/models/__init__.py$'
      - id: manage-py-lint
        name: lint check (ruff & mypy)
        entry: python manage.py lint --raise-error
        language: system
        files: \.py$
        exclude: '^render\.py$'
