services:
  insights-backend:
    container_name: insights-backend
    build:
      context: .
      dockerfile: insights_backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - insights_backend/.env
    command:
      - "run-server"
    healthcheck:
      test: curl --fail http://localhost:8000/insights/v1/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
