"""Added heuristic model and salient flag

Revision ID: 41b5bfa02be3
Revises: 341fea937737
Create Date: 2024-09-24 15:38:04.139804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41b5bfa02be3"
down_revision: str | None = "341fea937737"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story", sa.Column("is_salient", sa.Boolean(), nullable=True), schema="story_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story", "is_salient", schema="story_store")
    # ### end Alembic commands ###
