"""Added is_salient and story config model

Revision ID: 6847f7fa25a9
Revises: 341fea937737
Create Date: 2024-09-25 17:07:27.205145

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6847f7fa25a9"
down_revision: str | None = "341fea937737"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storyconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("story_type", sa.String(length=255), nullable=False),
        sa.Column("grain", sa.String(length=255), nullable=False),
        sa.Column("heuristic_expression", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_type", "grain", name="uix_story_types_grain"),
        schema="story_store",
    )
    op.add_column("story", sa.Column("is_salient", sa.Boolean(), nullable=True), schema="story_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story", "is_salient", schema="story_store")
    op.drop_table("storyconfig", schema="story_store")
    # ### end Alembic commands ###
