"""Added heuristic model

Revision ID: b970ca8f2c0a
Revises: 41b5bfa02be3
Create Date: 2024-09-24 16:00:50.147326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b970ca8f2c0a"
down_revision: str | None = "41b5bfa02be3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heuristicexpression",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("story_type", sa.String(length=255), nullable=False),
        sa.Column("grain", sa.String(length=255), nullable=False),
        sa.Column("expression", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_type", "grain", name="uix_story_type_grain"),
        schema="story_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("heuristicexpression", schema="story_store")
    # ### end Alembic commands ###
