"""Initial

Revision ID: 950a7cb18abb
Revises:
Create Date: 2024-08-07 14:55:35.677990

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "950a7cb18abb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column(
            "genre",
            sa.Enum(
                "GROWTH",
                "TRENDS",
                "PERFORMANCE",
                "BIG_MOVES",
                "ROOT_CAUSES",
                name="storygenre",
                schema="story_store",
                inherit_schema=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "story_group",
            sa.Enum(
                "GROWTH_RATES",
                "TREND_CHANGES",
                "TREND_EXCEPTIONS",
                "LONG_RANGE",
                "GOAL_VS_ACTUAL",
                "LIKELY_STATUS",
                "RECORD_VALUES",
                "STATUS_CHANGE",
                "SEGMENT_DRIFT",
                "REQUIRED_PERFORMANCE",
                "SIGNIFICANT_SEGMENTS",
                "COMPONENT_DRIFT",
                name="storygroup",
                schema="story_store",
                inherit_schema=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "story_type",
            sa.Enum(
                "SLOWING_GROWTH",
                "ACCELERATING_GROWTH",
                "STABLE_TREND",
                "NEW_UPWARD_TREND",
                "NEW_DOWNWARD_TREND",
                "PERFORMANCE_PLATEAU",
                "SPIKE",
                "DROP",
                "IMPROVING_PERFORMANCE",
                "WORSENING_PERFORMANCE",
                "ON_TRACK",
                "OFF_TRACK",
                "IMPROVING_STATUS",
                "WORSENING_STATUS",
                "REQUIRED_PERFORMANCE",
                "HOLD_STEADY",
                "RECORD_HIGH",
                "RECORD_LOW",
                "LIKELY_ON_TRACK",
                "LIKELY_OFF_TRACK",
                "GROWING_SEGMENT",
                "SHRINKING_SEGMENT",
                "IMPROVING_SEGMENT",
                "WORSENING_SEGMENT",
                "TOP_4_SEGMENTS",
                "BOTTOM_4_SEGMENTS",
                "IMPROVING_COMPONENT",
                "WORSENING_COMPONENT",
                name="storytype",
                schema="story_store",
                inherit_schema=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "grain",
            sa.Enum("DAY", "WEEK", "MONTH", "QUARTER", "YEAR", name="grain", schema="story_store", inherit_schema=True),
            nullable=True,
        ),
        sa.Column("metric_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_template", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("detail_template", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("series", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("story_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="story_store",
    )
    op.create_index(op.f("ix_story_store_story_genre"), "story", ["genre"], unique=False, schema="story_store")
    op.create_index(op.f("ix_story_store_story_grain"), "story", ["grain"], unique=False, schema="story_store")
    op.create_index(op.f("ix_story_store_story_metric_id"), "story", ["metric_id"], unique=False, schema="story_store")
    op.create_index(
        op.f("ix_story_store_story_story_date"), "story", ["story_date"], unique=False, schema="story_store"
    )
    op.create_index(
        op.f("ix_story_store_story_story_group"), "story", ["story_group"], unique=False, schema="story_store"
    )
    op.create_index(
        op.f("ix_story_store_story_story_type"), "story", ["story_type"], unique=False, schema="story_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_story_store_story_story_type"), table_name="story", schema="story_store")
    op.drop_index(op.f("ix_story_store_story_story_group"), table_name="story", schema="story_store")
    op.drop_index(op.f("ix_story_store_story_story_date"), table_name="story", schema="story_store")
    op.drop_index(op.f("ix_story_store_story_metric_id"), table_name="story", schema="story_store")
    op.drop_index(op.f("ix_story_store_story_grain"), table_name="story", schema="story_store")
    op.drop_index(op.f("ix_story_store_story_genre"), table_name="story", schema="story_store")
    op.drop_table("story", schema="story_store")
    # ### end Alembic commands ###
