"""stories_v2

Revision ID: a3298c4dc87f
Revises: 99590a208ae9
Create Date: 2025-04-01 15:20:28.319023

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3298c4dc87f"
down_revision: str | None = "99590a208ae9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("story", sa.Column("version", sa.Integer(), server_default="1", nullable=True), schema="story_store")
    op.add_column("story", sa.Column("pattern_run_id", sa.Integer(), nullable=True), schema="story_store")
    op.create_index(
        op.f("ix_story_store_story_pattern_run_id"), "story", ["pattern_run_id"], unique=False, schema="story_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_story_store_story_pattern_run_id"), table_name="story", schema="story_store")
    op.drop_column("story", "pattern_run_id", schema="story_store")
    op.drop_column("story", "version", schema="story_store")
    # ### end Alembic commands ###
