"""Add version to story config

Revision ID: 43e2678396ec
Revises: d99739f932b0
Create Date: 2025-08-14 16:30:40.299372

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43e2678396ec"
down_revision: str | None = "d99739f932b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "storyconfig", sa.Column("version", sa.Integer(), server_default="1", nullable=True), schema="story_store"
    )
    op.drop_constraint(op.f("uix_story_type_grain_tenant_id"), "storyconfig", schema="story_store", type_="unique")
    op.create_unique_constraint(
        "uix_story_type_grain_tenant_id_version",
        "storyconfig",
        ["story_type", "grain", "tenant_id", "version"],
        schema="story_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_story_type_grain_tenant_id_version", "storyconfig", schema="story_store", type_="unique")
    op.create_unique_constraint(
        op.f("uix_story_type_grain_tenant_id"),
        "storyconfig",
        ["story_type", "grain", "tenant_id"],
        schema="story_store",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("storyconfig", "version", schema="story_store")
    # ### end Alembic commands ###
