"""add index to story

Revision ID: f1d33692d75f
Revises: 43e2678396ec
Create Date: 2025-08-30 11:04:47.973219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1d33692d75f"
down_revision: str | None = "43e2678396ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_story_tenant_version_date_metric_grain_type",
        "story",
        ["tenant_id", "version", sa.literal_column("story_date DESC"), "metric_id", "grain", "story_type"],
        unique=False,
        schema="story_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_story_tenant_version_date_metric_grain_type", table_name="story", schema="story_store")
    # ### end Alembic commands ###
