"""add dimension name

Revision ID: 6bf7116f2849
Revises: f1d33692d75f
Create Date: 2025-09-16 21:31:34.398317

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bf7116f2849"
down_revision: str | None = "f1d33692d75f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story", sa.Column("dimension_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema="story_store"
    )
    op.create_index(
        op.f("ix_story_store_story_dimension_name"), "story", ["dimension_name"], unique=False, schema="story_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_story_store_story_dimension_name"), table_name="story", schema="story_store")
    op.drop_column("story", "dimension_name", schema="story_store")
    # ### end Alembic commands ###
