"""Added data column

Revision ID: ca2c2cc637f0
Revises: d99739f932b0
Create Date: 2025-05-13 13:07:55.011278

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca2c2cc637f0"
down_revision: str | None = "d99739f932b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story", sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema="story_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story", "data", schema="story_store")
    # ### end Alembic commands ###
