"""Add_columns_dimension_name_and_evaluation_pattern

Revision ID: 00e4e699cb18
Revises: f1d33692d75f
Create Date: 2025-09-25 10:17:09.235075

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00e4e699cb18"
down_revision: str | None = "f1d33692d75f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story", sa.Column("dimension_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema="story_store"
    )
    op.add_column(
        "story",
        sa.Column("evaluation_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        schema="story_store",
    )
    op.create_index(
        op.f("ix_story_store_story_dimension_name"), "story", ["dimension_name"], unique=False, schema="story_store"
    )
    op.create_index(
        op.f("ix_story_store_story_evaluation_pattern"),
        "story",
        ["evaluation_pattern"],
        unique=False,
        schema="story_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_story_store_story_evaluation_pattern"), table_name="story", schema="story_store")
    op.drop_index(op.f("ix_story_store_story_dimension_name"), table_name="story", schema="story_store")
    op.drop_column("story", "evaluation_pattern", schema="story_store")
    op.drop_column("story", "dimension_name", schema="story_store")
    # ### end Alembic commands ###
