[tool.poetry]
name = "query-manager"
version = "0.1.0"
description = "Query Manager for fulcrum intelligence"
authors = ["leverslabs"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = "^0.27.1"
gunicorn = "^21.2.0"
pydantic = { extras = ["email", "dotenv"], version = "^2.6.3" }
hupper = "^1.12.1"
rich = "^13.7.1"
typer = "^0.9.0"
watchgod = "^0.8.2"
httpx = "^0.27.0"
pydantic-settings = "^2.2.1"
aiofiles = "^23.2.1"
types-aiofiles = "^23.2.0.20240311"
pandas = "^2.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
