"""is stories enabled flag

Revision ID: edb1b49d5204
Revises: a52b9d4e6812
Create Date: 2024-12-19 13:21:13.282534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edb1b49d5204"
down_revision: str | None = "a52b9d4e6812"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenantconfig", sa.Column("is_stories_enabled", sa.Boolean(), nullable=True), schema="insights_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenantconfig", "is_stories_enabled", schema="insights_store")
    # ### end Alembic commands ###
