"""slack_config

Revision ID: a52b9d4e6812
Revises: 8431176dec35
Create Date: 2024-11-27 12:40:06.426027

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a52b9d4e6812"
down_revision: str | None = "8431176dec35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenantconfig",
        sa.Column("slack_connection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="insights_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenantconfig", "slack_connection", schema="insights_store")
    # ### end Alembic commands ###
