"""empty message

Revision ID: 6d1ad6f8baed
Revises: 0ec67649a45f
Create Date: 2024-09-25 15:15:50.181907

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d1ad6f8baed"
down_revision: str | None = "0ec67649a45f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant", sa.Column("external_org_id", sa.String(length=255), nullable=True), schema="insights_store")
    op.create_index(
        op.f("ix_insights_store_tenant_external_org_id"),
        "tenant",
        ["external_org_id"],
        unique=True,
        schema="insights_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_insights_store_tenant_external_org_id"), table_name="tenant", schema="insights_store")
    op.drop_column("tenant", "external_org_id", schema="insights_store")
    # ### end Alembic commands ###
