"""story creation flag

Revision ID: 16f7c08a6716
Revises: a52b9d4e6812
Create Date: 2024-12-18 22:19:52.568290

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16f7c08a6716"
down_revision: str | None = "a52b9d4e6812"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenantconfig", sa.Column("enable_story_creation", sa.Boolean(), nullable=True), schema="insights_store"
    )
    op.create_index(
        op.f("ix_insights_store_user_tenant_id"), "user", ["tenant_id"], unique=False, schema="insights_store"
    )
    op.drop_constraint("fk_user_tenant_id_tenant", "user", schema="insights_store", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_user_tenant_id_tenant",
        "user",
        "tenant",
        ["tenant_id"],
        ["id"],
        source_schema="insights_store",
        referent_schema="insights_store",
    )
    op.drop_index(op.f("ix_insights_store_user_tenant_id"), table_name="user", schema="insights_store")
    op.drop_column("tenantconfig", "enable_story_creation", schema="insights_store")
    # ### end Alembic commands ###
