"""notification_executions

Revision ID: d33517d50dab
Revises: 1bbb7c1d2a43
Create Date: 2025-02-26 18:40:28.369736

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d33517d50dab"
down_revision: str | None = "1bbb7c1d2a43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new statuses to ExecutionStatus enum in order
    op.execute("ALTER TYPE executionstatus ADD VALUE IF NOT EXISTS 'PENDING' BEFORE 'RUNNING'")
    op.execute("ALTER TYPE executionstatus ADD VALUE IF NOT EXISTS 'SCHEDULED' AFTER 'PENDING'")
    op.execute("ALTER TYPE executionstatus ADD VALUE IF NOT EXISTS 'PARTIAL' AFTER 'COMPLETED'")

    op.add_column(
        "notificationexecution",
        sa.Column("run_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'")),
        schema="insights_store",
    )
    op.add_column(
        "notificationexecution",
        sa.Column(
            "notification_type",
            sa.Enum("ALERT", "REPORT", name="notificationtype"),
            nullable=False,
            server_default="ALERT",
        ),
        schema="insights_store",
    )
    op.drop_column("notificationexecution", "recipients", schema="insights_store")
    op.add_column(
        "report", sa.Column("deployment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema="insights_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "deployment_id", schema="insights_store")
    op.add_column(
        "notificationexecution",
        sa.Column("recipients", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        schema="insights_store",
    )
    op.drop_column("notificationexecution", "notification_type", schema="insights_store")
    op.drop_column("notificationexecution", "run_info", schema="insights_store")

    # Note: We cannot remove enum values in PostgreSQL, so we don't remove PARTIAL in downgrade
    # ### end Alembic commands ###
