"""notification_deployment

Revision ID: d456a05eac0f
Revises: 1bbb7c1d2a43
Create Date: 2025-02-21 18:17:49.795855

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d456a05eac0f"
down_revision: str | None = "1bbb7c1d2a43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report", sa.Column("deployment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema="insights_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "deployment_id", schema="insights_store")
    # ### end Alembic commands ###
