"""update_notification_execution_fk_relationship

Revision ID: 7ebca88763ec
Revises: 2d2ee3555ee2
Create Date: 2025-03-28 15:42:56.613834

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ebca88763ec"
down_revision: str | None = "2d2ee3555ee2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_notificationexecution_alert_id_alert", "notificationexecution", schema="insights_store", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_notificationexecution_report_id_report",
        "notificationexecution",
        schema="insights_store",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "notificationexecution",
        "report",
        ["report_id"],
        ["id"],
        source_schema="insights_store",
        referent_schema="insights_store",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "notificationexecution",
        "alert",
        ["alert_id"],
        ["id"],
        source_schema="insights_store",
        referent_schema="insights_store",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notificationexecution", schema="insights_store", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "notificationexecution", schema="insights_store", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "fk_notificationexecution_report_id_report",
        "notificationexecution",
        "report",
        ["report_id"],
        ["id"],
        source_schema="insights_store",
        referent_schema="insights_store",
    )
    op.create_foreign_key(
        "fk_notificationexecution_alert_id_alert",
        "notificationexecution",
        "alert",
        ["alert_id"],
        ["id"],
        source_schema="insights_store",
        referent_schema="insights_store",
    )
    # ### end Alembic commands ###
