"""user_tenant_model

Revision ID: 2d2ee3555ee2
Revises: d33517d50dab
Create Date: 2025-03-20 20:00:35.737687

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d2ee3555ee2"
down_revision: str | None = "d33517d50dab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertenant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["insights_store.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tenant_id", name="uq_user_tenant"),
        schema="insights_store",
    )
    op.create_index(
        op.f("ix_insights_store_usertenant_tenant_id"),
        "usertenant",
        ["tenant_id"],
        unique=False,
        schema="insights_store",
    )
    op.execute("DROP POLICY IF EXISTS tenant_isolation_insights_store_user ON insights_store.user;")
    op.drop_index("ix_insights_store_user_tenant_id", table_name="user", schema="insights_store")
    op.drop_column("user", "tenant_id", schema="insights_store")
    op.execute("ALTER TABLE insights_store.usertenant ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation_insights_store_usertenant ON insights_store.usertenant USING (tenant_id = ("
        "SELECT current_setting('app.current_tenant')::int));"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("tenant_id", sa.INTEGER(), autoincrement=False, nullable=False), schema="insights_store"
    )
    op.create_index("ix_insights_store_user_tenant_id", "user", ["tenant_id"], unique=False, schema="insights_store")
    op.execute(
        "CREATE POLICY tenant_isolation_insights_store_user ON insights_store.user USING "
        "(tenant_id = (SELECT current_setting('app.current_tenant')::int));"
    )
    op.drop_index(op.f("ix_insights_store_usertenant_tenant_id"), table_name="usertenant", schema="insights_store")
    op.drop_table("usertenant", schema="insights_store")
    # ### end Alembic commands ###
