"""alerts_models_update

Revision ID: 1d106ab152cf
Revises: f764c6ac1ae0
Create Date: 2025-02-04 00:29:43.884306

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d106ab152cf"
down_revision: str | None = "f764c6ac1ae0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alert", sa.Column("is_published", sa.Boolean(), nullable=True), schema="insights_store")
    op.drop_column("alert", "schedule", schema="insights_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert",
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        schema="insights_store",
    )
    op.drop_column("alert", "is_published", schema="insights_store")
    # ### end Alembic commands ###
