[tool.poetry]
name = "commons"
version = "1.0.0"
description = "Commons package for leverslabs"
authors = ["leverslabs"]
license = "Proprietary"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = { extras = ["email", "dotenv"], version = "^2.7.0" }
httpx = "^0.27.0"
fastapi = {version = "^0.110.1"}
sqlalchemy = {version = "^2.0.29", optional = true}
sqlmodel = {version = "^0.0.16", optional = true}

[tool.poetry.extras]
db = ["sqlmodel", "sqlalchemy"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=commons"
filterwarnings = "ignore::DeprecationWarning"
