version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fulcrum_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  analysis_manager:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py run-prod-server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
