"""Metric Notifications

Revision ID: c217de56dd1a
Revises: 7e7a22650c1c
Create Date: 2024-11-27 14:37:48.051516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c217de56dd1a"
down_revision: str | None = "7e7a22650c1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metricnotifications",
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("slack_enabled", sa.Boolean(), nullable=True),
        sa.Column("slack_channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["query_store.metric.id"],
        ),
        sa.PrimaryKeyConstraint("metric_id"),
        schema="query_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metricnotifications", schema="query_store")
    # ### end Alembic commands ###
