"""metric_notification

Revision ID: 197233d812d4
Revises: 7e7a22650c1c
Create Date: 2024-12-04 17:06:55.528305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "197233d812d4"
down_revision: str | None = "7e7a22650c1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metricnotifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("slack_enabled", sa.Boolean(), nullable=True),
        sa.Column("slack_channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["query_store.metric.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("metric_id", "tenant_id", name="uq_metric_id_tenant_id_notify"),
        schema="query_store",
    )
    op.create_index(
        op.f("ix_query_store_metricnotifications_tenant_id"),
        "metricnotifications",
        ["tenant_id"],
        unique=False,
        schema="query_store",
    )
    op.execute("ALTER TABLE query_store.metricnotifications ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation_query_store_metricnotifications ON query_store.metricnotifications USING ("
        "tenant_id = current_setting('app.current_tenant')::int);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_query_store_metricnotifications_tenant_id"), table_name="metricnotifications", schema="query_store"
    )
    op.drop_table("metricnotifications", schema="query_store")
    # ### end Alembic commands ###
