"""Metrics-Dimensions-update

Revision ID: df37e94e143f
Revises: 620730dc8252
Create Date: 2024-07-24 17:39:31.226872

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "df37e94e143f"
down_revision: str | None = "620730dc8252"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
