"""Metrics-Dimensions-update-fk

Revision ID: 5b9be872d872
Revises: df37e94e143f
Create Date: 2024-07-24 17:58:16.928931

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5b9be872d872"
down_revision: str | None = "df37e94e143f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
