"""Initial

Revision ID: 2f09badbeb05
Revises:
Create Date: 2024-07-23 18:46:48.023567

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f09badbeb05"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dimensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("dimension_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", "dimension_id"),
        schema="query_store",
    )
    op.create_index(
        op.f("ix_query_store_dimensions_dimension_id"),
        "dimensions",
        ["dimension_id"],
        unique=True,
        schema="query_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_store_dimensions_dimension_id"), table_name="dimensions", schema="query_store")
    op.drop_table("dimensions", schema="query_store")
    # ### end Alembic commands ###
