"""add_hypothetical_max_field

Revision ID: 8ab2483681a2
Revises: 90cd84520fbd
Create Date: 2024-08-05 14:00:31.604093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ab2483681a2'
down_revision: Union[str, None] = '90cd84520fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('hypothetical_max', sa.Float(), nullable=True), schema='query_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric', 'hypothetical_max', schema='query_store')
    # ### end Alembic commands ###
