"""remove_metricnotifications

Revision ID: 856c810d6693
Revises: e6c112207861
Create Date: 2025-03-26 11:21:03.342926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "856c810d6693"
down_revision: str | None = "e6c112207861"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_query_store_metricnotifications_tenant_id", table_name="metricnotifications", schema="query_store"
    )
    op.drop_table("metricnotifications", schema="query_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metricnotifications",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("metric_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("slack_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("slack_channels", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["metric_id"], ["query_store.metric.id"], name="fk_metricnotifications_metric_id_metric"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_metricnotifications"),
        sa.UniqueConstraint("metric_id", "tenant_id", name="uq_metric_id_tenant_id_notify"),
        schema="query_store",
    )
    op.create_index(
        "ix_query_store_metricnotifications_tenant_id",
        "metricnotifications",
        ["tenant_id"],
        unique=False,
        schema="query_store",
    )
    # ### end Alembic commands ###
