"""add data snapshot columns

Revision ID: c826a9e3fe77
Revises: 88e0bdcc08be
Create Date: 2025-08-05 19:34:20.393791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c826a9e3fe77"
down_revision: str | None = "88e0bdcc08be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metric_sync_status", sa.Column("first_snapshot_date", sa.Date(), nullable=True), schema="query_store"
    )
    op.add_column("metric_sync_status", sa.Column("last_snapshot_date", sa.Date(), nullable=True), schema="query_store")
    op.create_index(
        "idx_metric_sync_status_data_range",
        "metric_sync_status",
        ["first_snapshot_date", "last_snapshot_date"],
        unique=False,
        schema="query_store",
    )
    op.add_column("tenant_sync_status", sa.Column("started_at", sa.DateTime(), nullable=True), schema="query_store")
    op.add_column("tenant_sync_status", sa.Column("ended_at", sa.DateTime(), nullable=True), schema="query_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_sync_status", "ended_at", schema="query_store")
    op.drop_column("tenant_sync_status", "started_at", schema="query_store")
    op.drop_index("idx_metric_sync_status_data_range", table_name="metric_sync_status", schema="query_store")
    op.drop_column("metric_sync_status", "last_snapshot_date", schema="query_store")
    op.drop_column("metric_sync_status", "first_snapshot_date", schema="query_store")
    # ### end Alembic commands ###
