"""Start date and end date added to tenant sync

Revision ID: a8bdf44e56f0
Revises: 88e0bdcc08be
Create Date: 2025-08-05 13:57:23.164121

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8bdf44e56f0"
down_revision: str | None = "88e0bdcc08be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant_sync_status", sa.Column("started_at", sa.DateTime(), nullable=True), schema="query_store")
    op.add_column("tenant_sync_status", sa.Column("ended_at", sa.DateTime(), nullable=True), schema="query_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_sync_status", "ended_at", schema="query_store")
    op.drop_column("tenant_sync_status", "started_at", schema="query_store")
    # ### end Alembic commands ###
