"""add unique constraint and aim field

Revision ID: 39823d5e1f03
Revises: 856c810d6693
Create Date: 2025-04-23 19:23:52.014512

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39823d5e1f03"
down_revision: str | None = "856c810d6693"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the aim field to the metric table - this is a new field
    op.add_column("metric", sa.Column("aim", sa.String(length=255), nullable=True), schema="query_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the aim field from metric table
    op.drop_column("metric", "aim", schema="query_store")
    # ### end Alembic commands ###
