"""data snapshot range

Revision ID: 5541c192c7d7
Revises: a8bdf44e56f0
Create Date: 2025-08-05 17:06:00.520012

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5541c192c7d7"
down_revision: str | None = "a8bdf44e56f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metric_sync_status", sa.Column("data_start_date", sa.Date(), nullable=True), schema="query_store")
    op.add_column("metric_sync_status", sa.Column("data_end_date", sa.Date(), nullable=True), schema="query_store")
    op.create_index(
        "idx_metric_sync_status_data_range",
        "metric_sync_status",
        ["data_start_date", "data_end_date"],
        unique=False,
        schema="query_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_metric_sync_status_data_range", table_name="metric_sync_status", schema="query_store")
    op.drop_column("metric_sync_status", "data_end_date", schema="query_store")
    op.drop_column("metric_sync_status", "data_start_date", schema="query_store")
    # ### end Alembic commands ###
