"""metric label not none

Revision ID: 1cc9dfb82062
Revises: c826a9e3fe77
Create Date: 2025-08-28 12:22:57.687672

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cc9dfb82062"
down_revision: str | None = "c826a9e3fe77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("metric", "label", existing_type=sa.VARCHAR(length=255), nullable=False, schema="query_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("metric", "label", existing_type=sa.VARCHAR(length=255), nullable=True, schema="query_store")
    # ### end Alembic commands ###
