"""Added aim field

Revision ID: 4d4be94c501c
Revises: 856c810d6693
Create Date: 2025-04-03 01:35:02.076955

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d4be94c501c"
down_revision: str | None = "856c810d6693"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("metric", sa.Column("aim", sa.String(length=255), nullable=True), schema="query_store")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric", "aim", schema="query_store")
    # ### end Alembic commands ###
