"""correlate_table

Revision ID: aa60f32deff2
Revises: 2365755b16e0
Create Date: 2024-03-08 18:35:46.803538

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa60f32deff2"
down_revision: str | None = "2365755b16e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correlate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.Column("metric_id_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric_id_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("correlation_coefficient", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_correlate_metric_id_1"), "correlate", ["metric_id_1"], unique=False)
    op.create_index(op.f("ix_correlate_metric_id_2"), "correlate", ["metric_id_2"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_correlate_metric_id_2"), table_name="correlate")
    op.drop_index(op.f("ix_correlate_metric_id_1"), table_name="correlate")
    op.drop_table("correlate")
    # ### end Alembic commands ###
