"""Initial

Revision ID: 4160240a18cb
Revises:
Create Date: 2024-07-30 16:57:08.412705

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4160240a18cb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correlate",
        sa.Column("metric_id_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric_id_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("correlation_coefficient", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="analysis_store",
    )
    op.create_index(
        op.f("ix_analysis_store_correlate_metric_id_1"),
        "correlate",
        ["metric_id_1"],
        unique=False,
        schema="analysis_store",
    )
    op.create_index(
        op.f("ix_analysis_store_correlate_metric_id_2"),
        "correlate",
        ["metric_id_2"],
        unique=False,
        schema="analysis_store",
    )
    op.create_table(
        "describe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("metric_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("dimension", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=False),
        sa.Column("median", sa.Float(), nullable=False),
        sa.Column("variance", sa.Float(), nullable=False),
        sa.Column("standard_deviation", sa.Float(), nullable=False),
        sa.Column("percentile_25", sa.Float(), nullable=False),
        sa.Column("percentile_50", sa.Float(), nullable=False),
        sa.Column("percentile_75", sa.Float(), nullable=False),
        sa.Column("percentile_90", sa.Float(), nullable=False),
        sa.Column("percentile_95", sa.Float(), nullable=False),
        sa.Column("percentile_99", sa.Float(), nullable=False),
        sa.Column("min", sa.Float(), nullable=False),
        sa.Column("max", sa.Float(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("sum", sa.Float(), nullable=False),
        sa.Column("unique", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="analysis_store",
    )
    op.create_index(
        op.f("ix_analysis_store_describe_dimension"), "describe", ["dimension"], unique=False, schema="analysis_store"
    )
    op.create_index(
        op.f("ix_analysis_store_describe_metric_id"), "describe", ["metric_id"], unique=False, schema="analysis_store"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_store_describe_metric_id"), table_name="describe", schema="analysis_store")
    op.drop_index(op.f("ix_analysis_store_describe_dimension"), table_name="describe", schema="analysis_store")
    op.drop_table("describe", schema="analysis_store")
    op.drop_index(op.f("ix_analysis_store_correlate_metric_id_2"), table_name="correlate", schema="analysis_store")
    op.drop_index(op.f("ix_analysis_store_correlate_metric_id_1"), table_name="correlate", schema="analysis_store")
    op.drop_table("correlate", schema="analysis_store")
    # ### end Alembic commands ###
