"""Add unique constraint to pattern config

Revision ID: 31d64a96baec
Revises: 26dce741ef30
Create Date: 2025-05-22 18:29:13.718242

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31d64a96baec"
down_revision: str | None = "26dce741ef30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pattern_configs",
        "needs_dimension_analysis",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
        schema="analysis_store",
    )
    op.drop_index(
        "ix_analysis_store_pattern_configs_pattern_name", table_name="pattern_configs", schema="analysis_store"
    )
    op.create_index(
        op.f("ix_analysis_store_pattern_configs_pattern_name"),
        "pattern_configs",
        ["pattern_name"],
        unique=False,
        schema="analysis_store",
    )
    op.create_unique_constraint(
        "uq_pattern_config_tenant_pattern_version",
        "pattern_configs",
        ["tenant_id", "pattern_name", "version"],
        schema="analysis_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_pattern_config_tenant_pattern_version",
        "pattern_configs",
        schema="analysis_store",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_analysis_store_pattern_configs_pattern_name"), table_name="pattern_configs", schema="analysis_store"
    )
    op.create_index(
        "ix_analysis_store_pattern_configs_pattern_name",
        "pattern_configs",
        ["pattern_name"],
        unique=True,
        schema="analysis_store",
    )
    op.alter_column(
        "pattern_configs",
        "needs_dimension_analysis",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
        schema="analysis_store",
    )
    # ### end Alembic commands ###
