"""pattern_run_dimensional

Revision ID: 26dce741ef30
Revises: d307ac9b5a88
Create Date: 2025-05-08 20:41:30.296645

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26dce741ef30"
down_revision: str | None = "d307ac9b5a88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pattern_results",
        sa.Column("dimension_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        schema="analysis_store",
    )
    op.drop_constraint("uq_pattern_results_metric_id", "pattern_results", schema="analysis_store", type_="unique")
    op.create_index(
        "idx_pattern_result_metric_tenant_grain_dimension",
        "pattern_results",
        ["metric_id", "tenant_id", "grain", "dimension_name"],
        unique=False,
        schema="analysis_store",
    )
    op.create_index(
        op.f("ix_analysis_store_pattern_results_dimension_name"),
        "pattern_results",
        ["dimension_name"],
        unique=False,
        schema="analysis_store",
    )
    op.create_unique_constraint(
        None,
        "pattern_results",
        ["metric_id", "tenant_id", "pattern", "version", "analysis_date", "grain", "dimension_name"],
        schema="analysis_store",
    )
    op.add_column(
        "pattern_configs",
        sa.Column("needs_dimension_analysis", sa.Boolean(), server_default="false"),
        schema="analysis_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pattern_configs", "needs_dimension_analysis", schema="analysis_store")
    op.drop_index(
        op.f("ix_analysis_store_pattern_results_dimension_name"), table_name="pattern_results", schema="analysis_store"
    )
    op.drop_index(
        "idx_pattern_result_metric_tenant_grain_dimension", table_name="pattern_results", schema="analysis_store"
    )
    op.create_unique_constraint(
        "uq_pattern_results_metric_id",
        "pattern_results",
        ["metric_id", "tenant_id", "pattern", "version", "analysis_date", "grain"],
        schema="analysis_store",
    )
    op.drop_column("pattern_results", "dimension_name", schema="analysis_store")
    # ### end Alembic commands ###
