"""pattern_config

Revision ID: be54d294ad1b
Revises: 3b0d322a598f
Create Date: 2025-04-04 14:29:37.696915

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be54d294ad1b"
down_revision: str | None = "3b0d322a598f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pattern_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("current_timestamp(0)"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("pattern_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data_sources", sa.JSON(), nullable=True),
        sa.Column("analysis_window", sa.JSON(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="analysis_store",
    )
    op.create_index(
        op.f("ix_analysis_store_pattern_configs_pattern_name"),
        "pattern_configs",
        ["pattern_name"],
        unique=True,
        schema="analysis_store",
    )
    op.create_index(
        op.f("ix_analysis_store_pattern_configs_tenant_id"),
        "pattern_configs",
        ["tenant_id"],
        unique=False,
        schema="analysis_store",
    )
    op.execute("ALTER TABLE analysis_store.pattern_configs ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation_analysis_store_pattern_configs ON analysis_store.pattern_configs "
        "USING (tenant_id = (SELECT current_setting('app.current_tenant')::int));"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analysis_store_pattern_configs_tenant_id"), table_name="pattern_configs", schema="analysis_store"
    )
    op.drop_index(
        op.f("ix_analysis_store_pattern_configs_pattern_name"), table_name="pattern_configs", schema="analysis_store"
    )
    op.drop_table("pattern_configs", schema="analysis_store")
    # ### end Alembic commands ###
