#!/usr/bin/env python3
"""
Super Simple Historical Story Generation - Based on run.py pattern

Just loops through dates and triggers pattern analysis.
Stories are auto-generated by existing Prefect event automation.

Usage: Update the configuration section below and run:
    python run_historical_stories.py
"""

import asyncio
import logging
import pprint
from datetime import date, timedelta

from commons.models.enums import Granularity
from tasks_manager.flows.pattern_analysis import trigger_run_pattern
from tasks_manager.tasks.query import fetch_metrics_for_tenant

logger = logging.getLogger(__name__)


def get_dates_for_grain(grain: Granularity) -> list[date]:
    """Get dates for July 1 - Aug 20, 2025 based on grain."""
    start_date = date(2025, 7, 1)
    end_date = date(2025, 9, 3)
    dates = []
    current = start_date

    while current <= end_date:
        if grain == Granularity.DAY:
            dates.append(current)
            current += timedelta(days=1)
        elif grain == Granularity.WEEK:
            if current.weekday() == 0:  # Monday
                dates.append(current)
            current += timedelta(days=1)
        elif grain == Granularity.MONTH:
            if current.day == 1:
                dates.append(current)
            # Jump to first of next month
            if current.month == 12:
                current = current.replace(year=current.year + 1, month=1, day=1)
            else:
                current = current.replace(month=current.month + 1, day=1)

    return dates


async def main():
    """Main execution - stories generated automatically by events."""

    # ====== CONFIGURATION - UPDATE THESE ======
    tenant_id = 1
    all_metrics = await fetch_metrics_for_tenant(tenant_id)
    exclude_metric_ids = ["ct_won_opportunities_ent", "total_won_acv", "ct_churned_renewals",
                          "ct_contraction_renewals", "ct_expansion_renewals", "contraction_share_of_renewals",
                          "flat_share_of_renewals", "ct_flat_renewals", "expansion_share_of_renewals",
                          "total_incremental_renewal_arr"]
    metric_ids = [metric["metric_id"] for metric in all_metrics if metric["metric_id"] not in exclude_metric_ids]
    # metric_ids = ["ct_inquiries", "ct_opened_opportunities", "ct_qualified_leads", "ct_sales_qualified_opportunities"]
    patterns = ["forecasting"]
    grains = [Granularity.WEEK]
    dimensions = [
        "enterprise_lifecycle_stage",
        "enterprise_lifecycle_status",
        "disqualification_reason",
        "nurture_reason",
        "marketing_qualified_lead_type",
        "vercel_development_representative_sales_segment",
        "first_vercel_development_representative_sales_segment",
        "is_outreach_activity_sequenced",
        "agent_qualification",
        "is_inquiry",
        "is_mql",
        "is_qualified_lead",
        "is_swl",
        "is_sql_stage",
        "is_sqo",
        "is_disqualified",
        "vercel_development_representative_manager_name",
        "lead_stage",
        "opportunity_type",
        "record_type",
        "sales_development_representative_type",
        "customer_success_manager_region",
        "renewal_ownership_path",
        "renewal_manager_name",
        "is_technical_consultant_attached",
        "technical_consultant_name",
        "reseller_partner",
        "opportunity_source",
        "pipeline_source",
        "prospector_source",
        "pipeline_source_campaign_program",
        "is_inbound_request_contact",
        "is_marketing_qualified",
        "is_product_qualified",
        "marketing_qualified_lead_type",
        "opportunity_status",
        "qualified_meeting_details_disposition",
        "is_sales_qualified",
        "is_closed",
        "is_won",
        "is_lost",
        "is_qualification_no_show",
        "content_delivery_network",
        "database_management_system",
        "frontend_framework",
        "image_optimization_system",
        "log_drain_system",
        "version_control_system",
        "primary_product_interest",
        "secondary_product_interest",
        "forecast_type",
        "forecast_category",
        "renewal_outcome_forecast",
        "is_multi_year_contract",
        "renewal_manager_id",
        "technical_consultant_id",
        "renewal_stage",
        "is_new_business_opportunity",
        "is_upgrade_opportunity",
        "is_in_term_expansion_opportunity",
        "is_renewal_opportunity",
        "is_anniversary_opportunity",
        "is_marketing_sourced",
        "is_ae_sourced",
        "is_sdr_sourced",
        "is_flat_renewal",
        "is_contraction_renewal",
        "is_expansion_renewal",
        "is_successful_renewal",
        "is_failed_renewal",
        "is_won_anniversary",
        "is_qualification_meeting_booked",
        "is_qualification_meeting_held",
        "sqo_win_cohort"
    ]
    #
    # # ===========================================
    #
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
    logger.info("Starting historical story generation...")
    logger.info(f"Tenant: {tenant_id}")
    logger.info(f"Metrics: {metric_ids}")
    logger.info(f"Patterns: {patterns}")
    logger.info(f"Grains: {[g.value for g in grains]}")

    total_triggers = 0

    for pattern in patterns:
        for metric_id in metric_ids:
            for grain in grains:
                dates = get_dates_for_grain(grain)
                logger.info(f"============Processing {metric_id}/{pattern}/{grain.value}: {len(dates)} dates")

                for i, analysis_date in enumerate(dates, 1):
                    try:
                        logger.info(f"  [{i}/{len(dates)}] Triggering for {analysis_date}")
                        if pattern == "dimension_analysis":
                            for dimension in dimensions:
                                await trigger_run_pattern(
                                    tenant_id=tenant_id,
                                    pattern_name=pattern,
                                    metric_id=metric_id,
                                    grain=grain,
                                    dimension_name=dimension,
                                    analysis_date=analysis_date
                                )
                        else:
                            await trigger_run_pattern(
                                tenant_id=tenant_id,
                                pattern_name=pattern,
                                metric_id=metric_id,
                                grain=grain,
                                dimension_name=None,
                                analysis_date=analysis_date
                            )
                        total_triggers += 1

                    except Exception as e:
                        logger.error(f"  Failed for {analysis_date}: {e}")
                        continue

    logger.info(f"Completed! Total triggers: {total_triggers}")
    logger.info("Stories will be auto-generated by Prefect event automation.")
    logger.info("Check Prefect UI at http://localhost:4200 for progress.")


if __name__ == "__main__":
    asyncio.run(main())
