name: Code Quality and Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Code Quality and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependency Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install "poetry<2.0.0"

      - name: Install Top Level Dependencies
        run: |
          echo "Installing top level dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes --with dev
          pip install -U -r requirements.txt

      - name: Install Commons Dependencies
        run: |
          echo "Installing commons dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C commons
          pip install -U -r requirements.txt

      - name: Install Levers Dependencies
        run: |
          echo "Installing levers dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C levers
          pip install -U -r requirements.txt

      - name: Install Insights Backend Dependencies
        run: |
          echo "Installing insights_backend dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C insights_backend
          pip install -U -r requirements.txt

      - name: Install Analysis Manager Dependencies
        run: |
          echo "Installing analysis_manager dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C analysis_manager
          pip install -U -r requirements.txt

      - name: Install Query Manager Dependencies
        run: |
          echo "Installing query_manager dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C query_manager
          pip install -U -r requirements.txt


      - name: Install Story Manager Dependencies
        run: |
          echo "Installing story_manager dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C story_manager
          pip install -U -r requirements.txt

      - name: Install Core Dependencies
        run: |
          echo "Installing core dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C core
          pip install -U -r requirements.txt

      - name: Check Code Formatting
        run: |
          python manage.py format --check .

      - name: Check Linting Errors
        run: |
          export PYTHONPATH=`pwd`
          python manage.py lint --raise-error .

      - name: Run Unit Tests and Coverage @ Commons
        run: |
          export PYTHONPATH=`pwd`
          make test app=commons

      - name: Run Unit Tests and Coverage @ Levers
        run: |
          export PYTHONPATH=`pwd`
          make test app=levers

      - name: Run Unit Tests and Coverage @ Core
        run: |
          export PYTHONPATH=`pwd`
          make test app=core

      - name: Run Unit Tests and Coverage @ Insights Backend
        run: |
          export PYTHONPATH=`pwd`
          make test app=insights_backend

      - name: Run Unit Tests and Coverage @ Analysis Manager
        run: |
          export PYTHONPATH=`pwd`
          make test app=analysis_manager

      - name: Run Unit Tests and Coverage @ Query Manager
        run: |
          export PYTHONPATH=`pwd`
          make test app=query_manager

      - name: Run Unit Tests and Coverage @ Story Manager
        run: |
          export PYTHONPATH=`pwd`
          make test app=story_manager
