name: Deploy to AWS Lambda

on:
  # Targeting the insight-backend branch on each push
  push:
    branches:
      - LEV-389_workflow_CICD_pipeline
  # In case of a merge to main branch we will deploy all the modules
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main

#  TAG: $(date +%Y%m%d_%H%M%S)

permissions:
  id-token: write
  contents: read  # Adjust other permissions as needed

jobs:

  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_id: ${{ steps.commit_hash.outputs.TAG_ID }}
    steps:
      - name: Generate TAG
        id: generate_tag
        run: |
          echo "TAG_ID=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT

  build-insight-backend-image:
    needs: generate-tag
    uses: ./.github/workflows/reusable-build-image.yml
    with:
        ecr_repo: 'insights-backend'
        module_folder: 'insights_backend'
        tag: ${{ needs.generate-tag.outputs.TAG_ID }}

    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}

  deploy-insight-backend-image-on-lambda:
    needs: build-insight-backend-image
    uses: ./.github/workflows/reusable-lambda-deployment.yml
    with:
      ecr_repo: 'insights-backend'
      module_lambda_function_name: 'insights-backend-dev'
      tag: ${{ needs.generate-tag.outputs.TAG_ID }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
