name: Build and Deploy Insight Backend

on:
  push:
    branches:
      - main
      - 'surajpatil/lev-489-prod-grade-deployments'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Insight Backend Deployment environment choices'
        type: choice
        required: true
        options:
          - DEV
          - STAGING
          - PROD

env:
  app_name: "insights-backend"
  app_folder: "insights_backend"

permissions:
  id-token: write
  contents: read

jobs:
  set-vars:
    name: set-vars
    runs-on: ubuntu-latest

    outputs:
      ecr_repo: ${{ steps.set-vars.outputs.ecr_repo }}
      app_folder: ${{ steps.set-vars.outputs.app_folder }}
      app_name: ${{ steps.set-vars.outputs.app_name }}
      app_lambda_function_name: ${{ steps.set-vars.outputs.app_lambda_function_name }}
      env: ${{ steps.set-vars.outputs.env }}
      app_host: ${{ steps.set-vars.outputs.app_host }}
      migration: ${{ steps.set-vars.outputs.migration }}

    steps:
      - name: set-vars
        id: set-vars
        run: |
          echo "ecr_repo=$app_name" >> $GITHUB_OUTPUT
          echo "app_folder=$app_folder" >> $GITHUB_OUTPUT
          echo "app_name=$app_name" >> $GITHUB_OUTPUT
          echo "migration=true" >> $GITHUB_OUTPUT
          if ${{ github.event.inputs.environment == 'PROD'}}; then
            echo "app_host=https://${{ vars.PROD_INSIGHT_BACKEND_HOST }}" >> $GITHUB_OUTPUT;
            echo "app_lambda_function_name=${app_lambda_function_prefix}-prod" >> $GITHUB_OUTPUT;
            echo "env=prod" >> $GITHUB_OUTPUT;
          elif ${{ github.event.inputs.environment == 'STAGING' }}; then
            echo "app_host=https://${{ vars.STAGING_INSIGHT_BACKEND_HOST }}" >> $GITHUB_OUTPUT;
            echo "app_lambda_function_name=${app_lambda_function_prefix}-staging" >> $GITHUB_OUTPUT;
            echo "env=staging" >> $GITHUB_OUTPUT;
          else
            echo "app_host=https://${{ vars.DEV_INSIGHT_BACKEND_HOST }}" >> $GITHUB_OUTPUT;
            echo "app_lambda_function_name=${app_lambda_function_prefix}-dev" >> $GITHUB_OUTPUT;
            echo "env=dev" >> $GITHUB_OUTPUT;
          fi

  build_and_deploy:
    needs: set-vars
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
        ecr_repo: ${{ needs.set-vars.outputs.ecr_repo }}
        ecs_cluster: "fulcrum-intelligence"
        app_name: ${{ needs.set-vars.outputs.app_name }}
        app_folder: ${{ needs.set-vars.outputs.app_folder }}
        app_lambda_function_name: ${{ needs.set-vars.outputs.app_lambda_function_name }}
        app_host: ${{ needs.set-vars.outputs.app_host }}
        migration: ${{ needs.set-vars.outputs.migration }}
        env: ${{ needs.set-vars.outputs.env }}

    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
