name: Testing Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Leverlabs backend environment deployment choices'
        type: choice
        required: true
        options:
          - DEV
          - STAGING
          - PROD
  push:
    branches:
      - LEV-389_workflow_CICD_pipeline
jobs:
  manual-deployment:
    name: manual-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Triggering Dev Environment Workflows
        if: ${{ github.event.inputs.environment == 'DEV'}}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'manual-dev-deployment-trigger'
            })

      - name: Triggering Staging Environment Workflows
        if: ${{ github.event.inputs.environment == 'STAGING'}}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'manual-staging-deployment-trigger'
            })

      - name: Triggering Dev Environment Workflows
        if: ${{ github.event.inputs.environment == 'PROD'}}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'manual-prod-deployment-trigger'
            })
