name: Deploy Query Manager to AWS Lambda

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
    paths:
      - 'query_manager/**'
      - 'commons/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Query Manager Deployment environment choices'
        type: choice
        required: true
        options:
          - DEV
          - PROD2
          - PROD
  push:
    branches:
      - LEV-389_workflow_CICD_pipeline
    paths:
        - 'query_manager/**'
        - 'commons/**'

env:
  ecr_repo: "query-manager"
  app_name: "query_manager"
  app_lambda_function_name: "query-manager-dev"

permissions:
  id-token: write
  contents: read

jobs:
  set-vars:
    name: set-vars
    runs-on: ubuntu-latest

    outputs:
      ecr_repo: ${{ steps.set-vars.outputs.ecr_repo }}
      app_name: ${{ steps.set-vars.outputs.app_name }}
      app_lambda_function_name: ${{ steps.set-vars.outputs.app_lambda_function_name }}

    steps:
      - name: set-vars
        id: set-vars
        run: |
          echo "ecr_repo=$ecr_repo" >> $GITHUB_OUTPUT
          echo "app_name=$app_name" >> $GITHUB_OUTPUT
          echo "app_lambda_function_name=$app_lambda_function_name" >> $GITHUB_OUTPUT

  build_and_deploy:
    needs: set-vars
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
        ecr_repo: ${{ needs.set-vars.outputs.ecr_repo }}
        app_name: ${{ needs.set-vars.outputs.app_name }}
        app_lambda_function_name: ${{ needs.set-vars.outputs.app_lambda_function_name }}

    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
