name: Leverlabs Apps Database Migrations

on:
  workflow_call:
    inputs:
      app_name:
        description: 'One of the app folders containing the Dockerfile'
        required: true
        type: string
      ecr_repo:
        description: 'application ecr repo name'
        required: true
        type: string
      app_lambda_function_name:
        description: "One of the App's lambda function name"
        required: true
        type: string
      tag:
        description: 'Dynamically generated tag, format curdate_curtime'
        required: true
        type: string
      app_host:
        description: 'host url of the application'
        required: true
        type: string

    secrets:
      DATABASE_URL:
        description: 'Application DB url'
        required: true
      AWS_REGION:
        description: 'The region of ECR'
        required: true
      DEV_DEPLOYMENT_ROLE:
        description: 'The deployment role ARN (OIDC)'
        required: true
      ECR_REGISTRY:
        description: 'The ECR registry URL'
        required: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ${{ inputs.app_name }}
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install  # Or use pip if you're not using Poetry

      - name: Run migrations
        working-directory: ${{ inputs.app_name }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          poetry run python manage.py db upgrade

  deploy-image-on-lambda-with-migrations:
    needs: [ migrate ]
    uses: ./.github/workflows/reusable-lambda-deployment.yml
    with:
      ecr_repo: ${{ inputs.ecr_repo }}
      app_lambda_function_name: ${{ inputs.app_lambda_function_name }}
      tag: ${{ inputs.tag }}
      app_host: ${{ inputs.app_host }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
