name: Build & Deploy Application Service

on:
  workflow_call:
    inputs:
      app_name:
        description: 'The application name'
        required: true
        type: string
      app_folder:
        description: 'The application folder'
        required: true
        type: string
      ecr_repo:
        description: 'The ECR repository name'
        required: true
        type: string
      ecs_cluster:
        description: 'The ECS cluster name'
        required: true
        type: string
      env:
        description: 'The environment name'
        required: false
        type: string
        default: "dev"
      task_definition:
        description: 'The task definition file name'
        required: false
        type: string
        default: "web-task-definition.json"
      service_name:
        description: 'The service name'
        required: false
        type: string
        default: "web"

    secrets:
      ECR_REGISTRY:
        description: 'The ECR registry URL'
        required: true
      AWS_REGION:
        description: 'The AWS region'
        required: true
      DEV_DEPLOYMENT_ROLE:
        description: 'The deployment role ARN (OIDC)'
        required: true
      AWS_ACCOUNT_ID:
        description: 'The AWS account ID'
        required: true

jobs:
  generate-tag:
    name: Generate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Generate TAG
        id: generate-tag
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "tag_id=${COMMIT_HASH}_$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT
    outputs:
      tag_id: ${{ steps.generate-tag.outputs.tag_id }}

  build-image:
    needs: generate-tag
    uses: ./.github/workflows/reusable-build-image.yml
    with:
      ecr_repo: ${{ inputs.ecr_repo }}
      app_folder: ${{ inputs.app_folder }}
      tag: ${{ needs.generate-tag.outputs.tag_id }}
    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}

  deploy-web-service:
    needs: [build-image, generate-tag]
    uses: ./.github/workflows/reusable-cd-workflow.yml
    with:
      APP_NAME: ${{ inputs.app_name }}
      APP_FOLDER: ${{ inputs.app_folder }}
      TAG_ID: ${{ needs.generate-tag.outputs.tag_id }}
      SERVICE_NAME: ${{ inputs.service_name }}
      ECS_CLUSTER: ${{ inputs.ecs_cluster }}
      ECR_REPOSITORY: ${{ inputs.ecr_repo }}
      TASK_DEFINITION: ${{ inputs.task_definition }}
      ENV: ${{ inputs.env }}
    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ASSUME_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
