name: Leverlabs Apps Database Migrations

on:
  workflow_call:
    inputs:
      app_name:
        description: 'One of the app folders containing the Dockerfile'
        required: true
        type: string

    secrets:
      DATABASE_URL:
        description: 'Application DB url'
        required: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ${{ inputs.app_name }}
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install  # Or use pip if you're not using Poetry

      - name: Run migrations
        working-directory: ${{ inputs.app_name }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          poetry run python manage.py db upgrade
