name: Build and Upload Story Builder Image

on:
  push:
    branches:
      - main
    paths:
        - 'story_manager/**'
        - 'commons/**'
        - 'core/**'

  workflow_dispatch:

env:
  ecr_repo: "story-builder"
  ssm_path: "story-builder/workflow"
  app_name: "story_manager"

permissions:
  id-token: write
  contents: read

jobs:
  set-vars:
    name: set-vars
    runs-on: ubuntu-latest

    outputs:
      ecr_repo: ${{ steps.set-vars.outputs.ecr_repo }}
      app_name: ${{ steps.set-vars.outputs.app_name }}
      ssm_path: ${{ steps.set-vars.outputs.ssm_path }}

    steps:
      - name: set-vars
        id: set-vars
        run: |
          echo "ecr_repo=$ecr_repo" >> $GITHUB_OUTPUT
          echo "app_name=$app_name" >> $GITHUB_OUTPUT
          echo "ssm_path=$ssm_path" >> $GITHUB_OUTPUT

  generate-tag:
    name: generate-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Generate TAG
        id: generate-tag
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "tag_id=${COMMIT_HASH}_$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT
    outputs:
      tag_id: ${{ steps.generate-tag.outputs.tag_id }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [ set-vars, generate-tag ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
          role-session-name: OIDCSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build-and-push
        id: build-and-push
        working-directory: .
        run: |
          IMAGE="${{ secrets.ECR_REGISTRY }}/${{ needs.set-vars.outputs.ecr_repo }}:${{ needs.generate-tag.outputs.tag_id }}"

          echo "Building and tagging the image"
          docker build \
          -t $IMAGE \
          -f ${{ needs.set-vars.outputs.app_name }}/Dockerfile.story_builder .

          echo "Pushing Image to ECR"
          docker push $IMAGE
