name: Deploy Tasks Manager to Prefect Cloud

on:
  push:
    branches:
      - main
    paths:
      - "tasks_manager/**"
      - "commons/**"
      - "core/**"
      - "levers/**"
      - ".github/workflows/tasks-manager-deployment.yml"

  workflow_dispatch:
    inputs:
      environment:
        description: "Tasks Manager Deployment environment choices"
        type: choice
        required: true
        options:
          - DEV
          - STAGING
          - PROD

env:
  app_name: "tasks-manager"
  app_folder: "tasks_manager"

permissions:
  id-token: write
  contents: read

jobs:
  set-vars:
    name: set-vars
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.set-vars.outputs.app_name }}
      app_folder: ${{ steps.set-vars.outputs.app_folder }}
      ecr_repo: ${{ steps.set-vars.outputs.ecr_repo }}
      env: ${{ steps.set-vars.outputs.env }}
    steps:
      - name: set-vars
        id: set-vars
        run: |
          echo "app_folder=$app_folder" >> $GITHUB_OUTPUT
          echo "app_name=$app_name" >> $GITHUB_OUTPUT
          echo "ecr_repo=$app_name" >> $GITHUB_OUTPUT
          if ${{ github.event.inputs.environment == 'PROD'}}; then
            echo "env=prod" >> $GITHUB_OUTPUT;
          elif ${{ github.event.inputs.environment == 'STAGING' }}; then
            echo "env=staging" >> $GITHUB_OUTPUT;
          else
            echo "env=dev" >> $GITHUB_OUTPUT;
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: [set-vars]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependency Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install "poetry<2.0.0"

      - name: Install Dependencies
        run: |
          echo "Installing dependencies"
          poetry export -f requirements.txt --output requirements.txt --without-hashes -C tasks_manager
          pip install -U -r requirements.txt

      - name: Register Prefect blocks
        working-directory: ${{ needs.set-vars.outputs.app_folder }}
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          prefect blocks register --file tasks_manager/config.py

      - name: Deploy to Prefect Cloud
        working-directory: ${{ needs.set-vars.outputs.app_folder }}
        run: |
          prefect --no-prompt deploy --all
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

  build_and_push_image:
    needs: [set-vars, deploy]
    uses: ./.github/workflows/reusable-ci-cd.yml
    with:
        ecr_repo: ${{ needs.set-vars.outputs.ecr_repo }}
        ecs_cluster: "fulcrum-tasks-orchestrator"
        app_name: ${{ needs.set-vars.outputs.app_name }}
        app_folder: ${{ needs.set-vars.outputs.app_folder }}
        env: ${{ needs.set-vars.outputs.env }}
        task_definition: "prefect-worker-task-definition.json"
        service_name: "prefect-worker"

    secrets:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DEV_DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
